version: "3.2"
services:

  ch-server-1:
    image: yandex/clickhouse-server
    volumes:
#    - ./pp01/storage:/var/lib/clickhouse
    - ./pp01/pp_ch01_macros.xml:/etc/clickhouse-server/config.d/macros.xml
    - ./config.xml:/etc/clickhouse-server/config.xml
    - ./users.xml:/etc/clickhouse-server/users.d/users.xml
    - ./remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
    ports:
      - 8123:8123

  ch-server-2:
    image: yandex/clickhouse-server
    volumes:
#    - ./pp02/storage:/var/lib/clickhouse
    - ./pp02/pp_ch02_macros.xml:/etc/clickhouse-server/config.d/macros.xml
    - ./config.xml:/etc/clickhouse-server/config.xml
    - ./users.xml:/etc/clickhouse-server/users.d/users.xml
    - ./remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
    ports:
      - 8133:8123

  ch-server-3:
    image: yandex/clickhouse-server
    volumes:
#    - ./pp03/storage:/var/lib/clickhouse
    - ./pp03/pp_ch03_macros.xml:/etc/clickhouse-server/config.d/macros.xml
    - ./config.xml:/etc/clickhouse-server/config.xml
    - ./users.xml:/etc/clickhouse-server/users.d/users.xml
    - ./remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
    ports:
      - 8143:8123

  ch-server-4:
    image: yandex/clickhouse-server
    volumes:
#    - ./pp04/storage:/var/lib/clickhouse
    - ./pp04/pp_ch04_macros.xml:/etc/clickhouse-server/config.d/macros.xml
    - ./config.xml:/etc/clickhouse-server/config.xml
    - ./users.xml:/etc/clickhouse-server/users.d/users.xml
    - ./remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
    ports:
      - 8153:8123

  ch-client:
    image: yandex/clickhouse-client
    entrypoint:
    - /bin/sleep
    command:
    - infinity
  zookeeper:
    image: zookeeper

